# Generated by Django 4.2.10 on 2024-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
