# Generated by Django 4.2.10 on 2024-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_photoreport_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreport',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
