# Generated by Django 4.2.10 on 2024-03-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_photoreport_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreport',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
