# Generated by Django 4.2.10 on 2024-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_photoreport_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreport',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
